spring.application.name=ecomerce-app
spring.data.mongodb.uri=mongodb+srv://anishkt20:6Qex9oX69qmowJQY@cluster0.qfkb5aj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=eCommerce